import type { Major } from "./constants";
import type { Year } from "./storage";

export type MajorToPage = Partial<Record<Major, number>>;
export type PageToMajors = Partial<Record<number, Major[]>>;

export const YEAR_TO_MAJOR_TO_PAGE: {
  [K in Year]: MajorToPage;
} = {
  2023: {
    "help-p": 4,
    "help-h": 5,
    "help-af": 6,
    "help-l": 7,
    ccc: 8,
    jpjp: 9,
    "jpjp-jltt": 10,
    "css-s": 17,
    "css-l": 18,
    "css-ps": 19,
    "css-e": 20,
    "cis-ir": 21,
    "cis-id": 22,
    edu: 34,
    psy: 35,
    ds: 36,
    biol: 43,
    bres: 44,
    "bres-as": 45,
    "earth-gs": 46,
    "earth-ees": 47,
    // 48 生物学類 生命環境学際プログラム
    "bres-les": 49,
    "earth-les": 50,
    math: 62,
    physics: 63,
    chem: 64,
    "coens-ap": 65,
    "coens-eqe": 66,
    "coens-mse": 67,
    "coens-mme": 68,
    "esys-ies": 69,
    "esys-eme": 70,
    "pops-ses": 71,
    "pops-mse": 72,
    "pops-urp": 73,
    coins: 83,
    "coins-cs": 84,
    "coins-mimt": 85,
    mast: 86,
    "klis-science": 87,
    "klis-system": 87,
    "klis-rm": 88,
    med: 93,
    "med-new": 94,
    "med-2": 95,
    "med-2-new": 96,
    "nurse-n": 97,
    "nurse-phn": 98,
    "nurse-h": 99,
    "meds-ms": 100,
    "meds-ims": 101,
    "meds-mspis": 102,
    pe: 109,
    art: 113,
    "art-jad": 114,
  },
  2024: {
    "help-p": 4,
    "help-h": 5,
    "help-af": 6,
    "help-l": 7,
    ccc: 8,
    jpjp: 9,
    "jpjp-jltt": 10,
    "css-s": 18,
    "css-l": 19,
    "css-ps": 20,
    "css-e": 21,
    "cis-ir": 22,
    "cis-id": 23,
    edu: 35,
    psy: 36,
    ds: 37,
    biol: 44,
    bres: 45,
    "bres-as": 46,
    "earth-gs": 47,
    "earth-ees": 48,
    // 49 生物学類 生命環境学際プログラム
    "bres-les": 50,
    "earth-les": 51,
    math: 63,
    physics: 64,
    chem: 65,
    "coens-ap": 66,
    "coens-eqe": 67,
    "coens-mse": 68,
    "coens-mme": 69,
    "esys-ies": 70,
    "esys-eme": 71,
    "pops-ses": 72,
    "pops-mse": 73,
    "pops-urp": 74,
    coins: 84,
    "coins-cs": 85,
    "coins-mimt": 86,
    mast: 87,
    "klis-science": 88,
    "klis-system": 88,
    "klis-rm": 89,
    med: 94,
    "med-new": 95,
    "med-2": 96,
    "med-2-new": 97,
    "nurse-n": 98,
    "nurse-phn": 99,
    "nurse-h": 100,
    "meds-ms": 101,
    "meds-ims": 102,
    "meds-mspis": 103,
    pe: 110,
    art: 114,
    "art-jad": 115,
  },
  2025: {
    "help-p": 5,
    "help-h": 6,
    "help-af": 7,
    "help-l": 8,
    ccc: 9,
    jpjp: 10,
    "jpjp-jltt": 11,
    "css-s": 19,
    "css-l": 20,
    "css-ps": 21,
    "css-e": 22,
    "cis-ir": 23,
    "cis-id": 24,
    edu: 36,
    psy: 37,
    ds: 38,
    biol: 46,
    // 46 生物学類 生命環境学際プログラム
    bres: 47,
    "bres-as": 48,
    "bres-les": 49,
    "earth-gs": 50,
    "earth-ees": 51,
    "earth-les": 52,
    math: 64,
    physics: 65,
    chem: 66,
    "coens-ap": 67,
    "coens-eqe": 68,
    "coens-mse": 69,
    "coens-mme": 70,
    "esys-ies": 71,
    "esys-eme": 72,
    "pops-ses": 73,
    "pops-mse": 74,
    "pops-urp": 75,
    coins: 85,
    "coins-cs": 86,
    "coins-mimt": 87,
    mast: 88,
    "klis-science": 89,
    "klis-system": 89,
    "klis-rm": 90,
    med: 95,
    "med-new": 96,
    "med-2": 97,
    "med-2-new": 98,
    "nurse-n": 99,
    "nurse-phn": 100,
    "nurse-h": 101,
    "meds-ms": 102,
    "meds-ims": 103,
    "meds-mspis": 104,
    pe: 111,
    art: 116,
    "art-jad": 117,
  },
};

function transpose(majorToPage: MajorToPage): PageToMajors {
  const pageToMajors: PageToMajors = {};
  for (const [major, page] of Object.entries(majorToPage)) {
    const majors = pageToMajors[page];
    if (majors === undefined) pageToMajors[page] = [major as Major];
    else majors.push(major as Major);
  }
  return pageToMajors;
}

export const YEAR_TO_PAGE_TO_MAJORS: { [K in Year]: PageToMajors } = {
  2023: transpose(YEAR_TO_MAJOR_TO_PAGE[2023]),
  2024: transpose(YEAR_TO_MAJOR_TO_PAGE[2024]),
  2025: transpose(YEAR_TO_MAJOR_TO_PAGE[2025]),
};
